"""Planner package skeleton for ShardGrid."""

from .memory import (
    MemoryEstimationConfig,
    StageMemoryFit,
    build_model_profile,
    dtype_bytes,
    estimate_stage_memory,
    evaluate_stage_memory_fit,
    normalize_dtype_name,
)
from .partitioning import (
    CandidateValidationResult,
    PartitionCandidate,
    PartitionGenerationResult,
    StageCommunicationEdge,
    StagePartition,
    build_partition_profile,
    discover_partition_support,
    generate_partition_candidates,
    validate_partition_candidate,
)
from .requirements import (
    CommunicationRequirement,
    ConstraintViolation,
    FeasibilityStatus,
    MemoryConstraint,
    ParallelPlanningRequirements,
    PlacementFeasibilityResult,
    PlacementRequirements,
    WorkerEligibilityRequirements,
    WorkerEligibilityResult,
    evaluate_worker_eligibility,
    validate_partition_boundary,
    validate_placement_feasibility,
)

__all__ = [
    "MemoryEstimationConfig",
    "StageMemoryFit",
    "CommunicationRequirement",
    "ConstraintViolation",
    "build_model_profile",
    "build_partition_profile",
    "CandidateValidationResult",
    "dtype_bytes",
    "discover_partition_support",
    "estimate_stage_memory",
    "evaluate_stage_memory_fit",
    "FeasibilityStatus",
    "MemoryConstraint",
    "normalize_dtype_name",
    "PartitionCandidate",
    "PartitionGenerationResult",
    "ParallelPlanningRequirements",
    "PlacementFeasibilityResult",
    "PlacementRequirements",
    "StageCommunicationEdge",
    "StagePartition",
    "generate_partition_candidates",
    "WorkerEligibilityRequirements",
    "WorkerEligibilityResult",
    "evaluate_worker_eligibility",
    "validate_partition_candidate",
    "validate_partition_boundary",
    "validate_placement_feasibility",
]
