"""Planner package skeleton for ShardGrid."""

from .execution_plan import (
    build_automatic_parallel_plan,
    validate_automatic_parallel_plan,
    validate_automatic_parallel_plan_or_raise,
)
from .memory import (
    MemoryEstimationConfig,
    StageMemoryFit,
    build_model_profile,
    dtype_bytes,
    estimate_stage_memory,
    evaluate_stage_memory_fit,
    normalize_dtype_name,
)
from .partitioning import (
    CandidateValidationResult,
    PartitionCandidate,
    PartitionGenerationResult,
    StageCommunicationEdge,
    StagePartition,
    build_partition_profile,
    discover_partition_support,
    generate_partition_candidates,
    validate_partition_candidate,
)
from .placement import (
    JointPlacementPlan,
    StagePlacement,
    WorkerSubsetAttempt,
    search_joint_partition_placement,
)
from .requirements import (
    CommunicationRequirement,
    ConstraintViolation,
    FeasibilityStatus,
    MemoryConstraint,
    ParallelPlanningRequirements,
    PlacementFeasibilityResult,
    PlacementRequirements,
    WorkerEligibilityRequirements,
    WorkerEligibilityResult,
    evaluate_worker_eligibility,
    validate_partition_boundary,
    validate_placement_feasibility,
)
from .scoring import (
    PlanMemorySummary,
    select_best_joint_placement_plan,
    summarize_plan_memory_utilization,
)

__all__ = [
    "JointPlacementPlan",
    "MemoryEstimationConfig",
    "StageMemoryFit",
    "CommunicationRequirement",
    "ConstraintViolation",
    "build_model_profile",
    "build_partition_profile",
    "CandidateValidationResult",
    "dtype_bytes",
    "discover_partition_support",
    "estimate_stage_memory",
    "evaluate_stage_memory_fit",
    "FeasibilityStatus",
    "build_automatic_parallel_plan",
    "MemoryConstraint",
    "normalize_dtype_name",
    "PartitionCandidate",
    "PartitionGenerationResult",
    "ParallelPlanningRequirements",
    "PlanMemorySummary",
    "PlacementFeasibilityResult",
    "PlacementRequirements",
    "search_joint_partition_placement",
    "select_best_joint_placement_plan",
    "StageCommunicationEdge",
    "StagePlacement",
    "StagePartition",
    "summarize_plan_memory_utilization",
    "validate_automatic_parallel_plan",
    "validate_automatic_parallel_plan_or_raise",
    "generate_partition_candidates",
    "WorkerEligibilityRequirements",
    "WorkerEligibilityResult",
    "WorkerSubsetAttempt",
    "evaluate_worker_eligibility",
    "validate_partition_candidate",
    "validate_partition_boundary",
    "validate_placement_feasibility",
]
